# Generated by Django 5.1.6 on 2025-02-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardekho_app', '0006_review_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
    ]
